name: Java CI with Maven
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Checkout Alexandria
      uses: actions/checkout@v2
      with:
        repository: g2forge/alexandria
        path: alexandria
    - name: Build Alexandria
      working-directory: ./alexandria
      run: mvn -B install --file pom.xml -P release -DskipTests -Dgpg.skip
    - name: Checkout Habitat
      uses: actions/checkout@v2
      with:
        repository: g2forge/habitat
        path: habitat
    - name: Build Habitat
      working-directory: ./habitat
      run: mvn -B install --file pom.xml -P release -DskipTests -Dgpg.skip
    - name: Checkout Enigma
      uses: actions/checkout@v2
      with:
        repository: g2forge/enigma
        path: enigma
    - name: Build Enigma
      working-directory: ./enigma
      run: mvn -B install --file pom.xml -P release -DskipTests -Dgpg.skip
    - name: Checkout Gearbox
      uses: actions/checkout@v2
      with:
        repository: g2forge/gearbox
        path: gearbox
    - name: Build Gearbox
      working-directory: ./gearbox
      run: mvn -B install --file pom.xml -P release -DskipTests -Dgpg.skip
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: reassert
    - name: Build with Maven
      working-directory: ./reassert
      run: mvn -B package --file pom.xml -P release -Dgpg.skip